server:
  port: 9202
eureka:
  instance:
    # 该配置指示eureka客户端需要向eureka服务器发送心跳的频率  (Spring Cloud默认该配置是 30s)
    leaseRenewalIntervalInSeconds: 10
    # 该配置指示eureka服务器在接收到最后一个心跳之后等待的时间，然后才能从列表中删除此实例 (Spring Cloud默认该配置是 90s)
    lease-expiration-duration-in-seconds: 30
    # monitor
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      # 这里配置一个defaultZone 用来替换默认的配置 http://localhost:8761/eureka
      defaultZone: http://anytxnv2:9101/eureka

management:

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:

    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  #注册中心服务默认路由配置
          lower-case-service-id: true
    refresh:
      refreshable: none #解决Harika循环注入
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.101.28:3306/anytxnv2_gateway_admin?characterEncoding=utf8
    username: anydmp
    password: anydmp123